import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type'
}

// Simple HTML to PDF conversion (in production, use a proper PDF library)
function generatePermissionSlipHTML(data: any): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #F5C518;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .section {
      margin-bottom: 25px;
    }
    .section-title {
      font-weight: bold;
      font-size: 18px;
      margin-bottom: 10px;
      color: #0A0A0A;
    }
    .field {
      margin-bottom: 10px;
    }
    .field-label {
      font-weight: bold;
      display: inline-block;
      width: 150px;
    }
    .signature {
      border-top: 2px solid #000;
      width: 300px;
      margin-top: 50px;
      padding-top: 10px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Field Trip Permission Slip</h1>
    <p><strong>${data.experience.title}</strong></p>
  </div>

  <div class="section">
    <div class="section-title">Trip Information</div>
    <div class="field">
      <span class="field-label">Date:</span>
      <span>${data.trip.trip_date}</span>
    </div>
    <div class="field">
      <span class="field-label">Time:</span>
      <span>${data.trip.trip_time || 'TBD'}</span>
    </div>
    <div class="field">
      <span class="field-label">Location:</span>
      <span>${data.venue.name}</span>
    </div>
    <div class="field">
      <span class="field-label">Cost:</span>
      <span>$${(data.cost_cents / 100).toFixed(2)}</span>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Student Information</div>
    <div class="field">
      <span class="field-label">Name:</span>
      <span>${data.student.first_name} ${data.student.last_name}</span>
    </div>
    <div class="field">
      <span class="field-label">Grade:</span>
      <span>${data.student.grade}</span>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Parent/Guardian Information</div>
    <div class="field">
      <span class="field-label">Name:</span>
      <span>${data.parent.first_name} ${data.parent.last_name}</span>
    </div>
    <div class="field">
      <span class="field-label">Phone:</span>
      <span>${data.parent.phone}</span>
    </div>
    <div class="field">
      <span class="field-label">Email:</span>
      <span>${data.parent.email}</span>
    </div>
  </div>

  ${data.form_data?.medical_info ? `
  <div class="section">
    <div class="section-title">Medical Information</div>
    <div class="field">
      ${data.form_data.medical_info}
    </div>
  </div>
  ` : ''}

  <div class="section">
    <div class="section-title">Authorization</div>
    <p>
      I hereby give permission for my child to participate in the field trip described above.
      I understand that reasonable safety precautions will be taken at all times.
    </p>
    ${data.signature_data ? `
    <div class="signature">
      <img src="${data.signature_data}" alt="Signature" style="max-width: 250px;" />
      <div>Signed on: ${new Date(data.signed_at).toLocaleDateString()}</div>
    </div>
    ` : ''}
  </div>

  <div style="margin-top: 50px; text-align: center; color: #666; font-size: 12px;">
    <p>Generated by TripSlip on ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>
  `
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    const { permissionSlipId, type } = await req.json()

    // Get permission slip with all related data
    const { data: slip, error: slipError } = await supabase
      .from('permission_slips')
      .select(`
        *,
        trips (
          *,
          experiences (
            *,
            venues (*)
          ),
          teachers (*)
        ),
        students (*),
        parents:signed_by_parent_id (*)
      `)
      .eq('id', permissionSlipId)
      .single()

    if (slipError || !slip) {
      throw new Error('Permission slip not found')
    }

    // Generate HTML
    const html = generatePermissionSlipHTML({
      experience: slip.trips.experiences,
      venue: slip.trips.experiences.venues,
      trip: slip.trips,
      teacher: slip.trips.teachers,
      student: slip.students,
      parent: slip.parents,
      form_data: slip.form_data,
      signature_data: slip.signature_data,
      signed_at: slip.signed_at,
      cost_cents: slip.form_data?.cost_cents || 0
    })

    // In production, convert HTML to PDF using a library like puppeteer or wkhtmltopdf
    // For now, return HTML
    return new Response(html, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'text/html'
      },
      status: 200
    })
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400
      }
    )
  }
})
